name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-lib:
    name: Build library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - run: pnpm --filter @gh-actions/lib-a build
      - uses: actions/upload-artifact@v7
        with:
          name: lib-a-dist
          path: packages/lib-a/dist

  test-lib:
    name: Test library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - run: pnpm --filter @gh-actions/lib-a test

  test-app-a:
    name: Test app-a
    needs: [build-lib]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - uses: actions/download-artifact@v7
        with:
          name: lib-a-dist
          path: packages/lib-a/dist
      - run: pnpm --filter @gh-actions/app-a test

  test-app-b:
    name: Test app-b
    needs: [build-lib]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - uses: actions/download-artifact@v7
        with:
          name: lib-a-dist
          path: packages/lib-a/dist
      - run: pnpm --filter @gh-actions/app-b test
